### ISSUE TITLE
current-menu-item style not applied when the url is set to an html file

### ISSUE THREAD

**Issue by GreatEmerald** [ashutosh2k12/hcz-jekyll-blog#8]
In my current setup, I have a menu like this:
```yml
urls:
    - text: Home
      url: /index.html
      icon: fa-home
      layout: post
    - text: Articles
      url: /category/General articles.html
      icon: fa-file-text
    - text: About
      url: /about/index.html
      icon: fa-user
```
(This is because the server I'm using at the moment only displays pages that really exist, so just a link to /about/ or / would give a 404.)
This works fine, but the style of the menu button does not get the current-menu-item style applied to it when I visit the menu item.
